export { default as ApartmentCard } from './Home/components/ApartmentCard/ApartmentCard';
export { default as ApartmentSearch } from './Home/components/ApartmentSearch/ApartmentSearch';
export { default as ApparmentHero } from './Home/components/AparmentHero/ApparmentHero';
export { default as Form } from './Home/components/FormDiscounts/Form';
export * from './Home/components/Icons/Icons';
export { default as Slider } from './Home/components/Slider/Slider';
export * from './Home/components/WhyChooseUs/WhyChooseUs';
export * from './Home';
export { default as Login } from './Login/Login';
export { default as Register } from './Register/Register';
